package errorCodes

// ERROR CODES

const (
	OPERATION_SUCCESSFUL = 0
	NONEXISTENT_KEY      = 1
	OUT_OF_SPACE         = 2
	TEMP_SYSTEM_OVERLOAD = 3
	INTERNAL_KV_FAILURE  = 4
	UNRECOGNIZED_COMMAND = 5
	INVALID_KEY          = 6
	INVALID_VALUE        = 7
	MISSING_FIELDS       = 33
	UNNECESSARY_FIELDS   = 34
	UNIMPLEMENTED        = 35
	REPLICA_TIMEOUT      = 36
)
